# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: broker.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'broker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x62roker.proto\x12\x06\x62roker\"0\n\x0ePublishRequest\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\t\"%\n\x0fPublishResponse\x12\x12\n\nmessage_id\x18\x01 \x01(\t\"\xa7\x01\n\rBrokerMessage\x12\x12\n\nmessage_id\x18\x01 \x01(\t\x12\r\n\x05topic\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\x12\x13\n\x0b\x65nqueued_at\x18\x04 \x01(\x01\x12\x0f\n\x07retries\x18\x05 \x01(\x05\x12#\n\x05state\x18\x06 \x01(\x0e\x32\x14.broker.MessageState\x12\x1a\n\x12visibility_timeout\x18\x07 \x01(\x03\"\\\n\x0bNodeMessage\x12\x1a\n\x03\x61\x63k\x18\x01 \x01(\x0b\x32\x0b.broker.AckH\x00\x12&\n\theartbeat\x18\x02 \x01(\x0b\x32\x11.broker.HeartbeatH\x00\x42\t\n\x07payload\"\x19\n\x03\x41\x63k\x12\x12\n\nmessage_id\x18\x01 \x01(\t\" \n\nAckRequest\x12\x12\n\nmessage_id\x18\x01 \x01(\t\"\x1e\n\x0b\x41\x63kResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"=\n\x12\x44\x65\x61\x64LetterResponse\x12\'\n\x08messages\x18\x01 \x03(\x0b\x32\x15.broker.BrokerMessage\">\n\x13\x41llMessagesResponse\x12\'\n\x08messages\x18\x01 \x03(\x0b\x32\x15.broker.BrokerMessage\"\x07\n\x05\x45mpty\"\x1e\n\tHeartbeat\x12\x11\n\ttimestamp\x18\x01 \x01(\x03*Y\n\x0cMessageState\x12\x0c\n\x08\x45NQUEUED\x10\x00\x12\x0e\n\nPROCESSING\x10\x01\x12\x0c\n\x08INFLIGHT\x10\x02\x12\x10\n\x0c\x41\x43KNOWLEDGED\x10\x03\x12\x0b\n\x07RETRIED\x10\x04\x32\xaf\x02\n\x06\x42roker\x12:\n\x07Publish\x12\x16.broker.PublishRequest\x1a\x17.broker.PublishResponse\x12?\n\rMessageStream\x12\x13.broker.NodeMessage\x1a\x15.broker.BrokerMessage(\x01\x30\x01\x12.\n\x03\x41\x63k\x12\x12.broker.AckRequest\x1a\x13.broker.AckResponse\x12:\n\rGetDeadLetter\x12\r.broker.Empty\x1a\x1a.broker.DeadLetterResponse\x12<\n\x0eGetAllMessages\x12\r.broker.Empty\x1a\x1b.broker.AllMessagesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'broker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGESTATE']._serialized_start=638
  _globals['_MESSAGESTATE']._serialized_end=727
  _globals['_PUBLISHREQUEST']._serialized_start=24
  _globals['_PUBLISHREQUEST']._serialized_end=72
  _globals['_PUBLISHRESPONSE']._serialized_start=74
  _globals['_PUBLISHRESPONSE']._serialized_end=111
  _globals['_BROKERMESSAGE']._serialized_start=114
  _globals['_BROKERMESSAGE']._serialized_end=281
  _globals['_NODEMESSAGE']._serialized_start=283
  _globals['_NODEMESSAGE']._serialized_end=375
  _globals['_ACK']._serialized_start=377
  _globals['_ACK']._serialized_end=402
  _globals['_ACKREQUEST']._serialized_start=404
  _globals['_ACKREQUEST']._serialized_end=436
  _globals['_ACKRESPONSE']._serialized_start=438
  _globals['_ACKRESPONSE']._serialized_end=468
  _globals['_DEADLETTERRESPONSE']._serialized_start=470
  _globals['_DEADLETTERRESPONSE']._serialized_end=531
  _globals['_ALLMESSAGESRESPONSE']._serialized_start=533
  _globals['_ALLMESSAGESRESPONSE']._serialized_end=595
  _globals['_EMPTY']._serialized_start=597
  _globals['_EMPTY']._serialized_end=604
  _globals['_HEARTBEAT']._serialized_start=606
  _globals['_HEARTBEAT']._serialized_end=636
  _globals['_BROKER']._serialized_start=730
  _globals['_BROKER']._serialized_end=1033
# @@protoc_insertion_point(module_scope)
